openapi: 3.1.0
info:
  title: Arbiter API
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /v0/healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema: { type: string }

  /v0/contracts:
    get:
      summary: Contracts metadata (versions, action registry)
      responses:
        "200":
          description: Metadata
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /v0/events:
    post:
      summary: Submit Event
      description: Returns a deterministic ResponsePlan. Gate/AuthZ denials are represented as do_nothing action.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Event" }
      responses:
        "200":
          description: ResponsePlan
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ResponsePlan" }
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v0/generations:
    post:
      summary: Submit GenerationResult
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/GenerationResult" }
      responses:
        "200":
          description: ResponsePlan
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ResponsePlan" }
        "400":
          description: Invalid request payload
          content:
            application/json:
                schema: { $ref: "#/components/schemas/Error" }

  /v0/job-events:
    post:
      summary: Submit job lifecycle status event
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/JobStatusEvent" }
      responses:
        "200":
          description: ResponsePlan
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ResponsePlan" }
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v0/job-cancel:
    post:
      summary: Submit job cancellation request event
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/JobCancelRequest" }
      responses:
        "200":
          description: ResponsePlan
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ResponsePlan" }
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v0/approval-events:
    post:
      summary: Submit approval workflow event
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/ApprovalEvent" }
      responses:
        "200":
          description: ResponsePlan
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ResponsePlan" }
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

  /v0/action-results:
    post:
      summary: Report action execution result (optional in v0.0.1 but reserved)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Error" }

components:
  schemas:
    Event:
      type: object
      additionalProperties: false
      required: [v, event_id, tenant_id, source, room_id, actor, content, ts]
      properties:
        v: { type: integer, const: 0 }
        event_id: { type: string, minLength: 1 }
        tenant_id: { type: string, minLength: 1 }
        source: { type: string, minLength: 1 }
        room_id: { type: string, minLength: 1 }
        actor:
          type: object
          additionalProperties: false
          required: [type, id]
          properties:
            type: { enum: [human, service, system] }
            id: { type: string, minLength: 1 }
            roles: { type: array, items: { type: string } }
            claims: { type: object }
        content:
          type: object
          additionalProperties: false
          required: [type]
          properties:
            type: { enum: [text] }
            text: { type: string }
            reply_to: { anyOf: [{ type: string }, { type: "null" }] }
        ts: { type: string, format: date-time }
        extensions: { type: object }

    Action:
      type: object
      additionalProperties: false
      required: [type, action_id]
      properties:
        type:
          enum:
            [
              do_nothing,
              request_generation,
              send_message,
              send_reply,
              start_agent_job,
              request_approval,
            ]
        action_id: { type: string, minLength: 1 }
        target: { type: object }
        payload: { type: object }

    ResponsePlan:
      type: object
      additionalProperties: false
      required: [v, plan_id, tenant_id, room_id, actions]
      properties:
        v: { type: integer, const: 0 }
        plan_id: { type: string, minLength: 1 }
        tenant_id: { type: string, minLength: 1 }
        room_id: { type: string, minLength: 1 }
        actions:
          type: array
          minItems: 1
          items: { $ref: "#/components/schemas/Action" }
        policy_decisions: { type: array }
        debug: { type: object }

    GenerationResult:
      type: object
      additionalProperties: false
      required: [v, plan_id, action_id, tenant_id, text]
      properties:
        v: { type: integer, const: 0 }
        plan_id: { type: string, minLength: 1 }
        action_id: { type: string, minLength: 1 }
        tenant_id: { type: string, minLength: 1 }
        text: { type: string }
        trace_id: { anyOf: [{ type: string }, { type: "null" }] }

    JobStatusEvent:
      type: object
      additionalProperties: false
      required: [v, event_id, tenant_id, job_id, status, ts]
      properties:
        v: { type: integer, const: 0 }
        event_id: { type: string, minLength: 1 }
        tenant_id: { type: string, minLength: 1 }
        job_id: { type: string, minLength: 1 }
        status: { enum: [started, heartbeat, completed, failed, cancelled] }
        ts: { type: string, format: date-time }
        reason_code: { anyOf: [{ type: string }, { type: "null" }] }

    JobCancelRequest:
      type: object
      additionalProperties: false
      required: [v, event_id, tenant_id, job_id, ts]
      properties:
        v: { type: integer, const: 0 }
        event_id: { type: string, minLength: 1 }
        tenant_id: { type: string, minLength: 1 }
        job_id: { type: string, minLength: 1 }
        ts: { type: string, format: date-time }
        reason_code: { anyOf: [{ type: string }, { type: "null" }] }

    ApprovalEvent:
      type: object
      additionalProperties: false
      required: [v, event_id, tenant_id, approval_id, status, ts]
      properties:
        v: { type: integer, const: 0 }
        event_id: { type: string, minLength: 1 }
        tenant_id: { type: string, minLength: 1 }
        approval_id: { type: string, minLength: 1 }
        status: { enum: [requested, approved, rejected, expired] }
        ts: { type: string, format: date-time }
        reason_code: { anyOf: [{ type: string }, { type: "null" }] }

    Error:
      type: object
      additionalProperties: false
      required: [error]
      properties:
        error:
          type: object
          additionalProperties: false
          required: [code, message]
          properties:
            code: { type: string }
            message: { type: string }
