openapi: 3.1.0
info:
  title: Arbiter API
  version: 1.2.1
servers:
  - url: http://localhost:8080
paths:
  /v1/healthz:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /v1/contracts:
    get:
      summary: Contracts and governance discovery
      responses:
        "200":
          description: Contracts metadata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContractsMetadata"

  /v1/events:
    post:
      summary: Submit provider-agnostic event envelope
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: Generated plan envelope
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Plan"
        "400":
          description: Invalid request or policy rejection
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Idempotency payload mismatch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/approval-events:
    post:
      summary: Submit approval lifecycle event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApprovalEvent"
      responses:
        "204":
          description: Accepted
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/action-results:
    post:
      summary: Submit action execution result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActionResult"
      responses:
        "204":
          description: Accepted
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Idempotency payload mismatch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Event:
      $ref: "../contracts/v1/ops.event.schema.json"
    Action:
      $ref: "../contracts/v1/ops.action.schema.json"
    Plan:
      $ref: "../contracts/v1/ops.plan.schema.json"
    ApprovalEvent:
      $ref: "../contracts/v1/ops.approval_event.schema.json"
    ActionResult:
      $ref: "../contracts/v1/ops.action_result.schema.json"
    ContractsMetadata:
      $ref: "../contracts/v1/ops.contracts_metadata.schema.json"
    Error:
      $ref: "../contracts/v1/ops.errors.schema.json"
